services:
  orderdb:
    container_name: order-db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  order_service:
    container_name: order-service
    image: amjadfqs/g1_a_order_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - orderdb
