spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true # Set to true to see SQL queries in console
    properties:
      hibernate:
        format_sql: true # Format SQL queries in console

server:
  port: 8080 # Set your desired port number
