spring:
  config:
    import: optional:secrets.properties
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true # Set to true to see SQL queries in console
    properties:
      hibernate:
        format_sql: true # Format SQL queries in console

server:
  port: ${SERVER_PORT}
  error:
    include-message: ALWAYS

customer:
  url: ${CUSTOMER_SERVICE_URL}
  error:
    include-message: ALWAYS

restaurant:
  url: ${RESTAURANT_SERVICE_URL}
  error:
    include-message: ALWAYS
mail:
  token: ${TOKEN}
  domain: ${DOMAIN}
  sender: ${SENDER}

