apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: restaurant-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: "restaurant"
        - name: MYSQL_USER
          value: "restaurant_user"
        - name: MYSQL_PASSWORD
          value: "restaurant_user_password"
        - name: MYSQL_ROOT_PASSWORD
          value: "hello"
        - name: MARIADB_MYSQL_LOCALHOST_USER
          value: "true"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: restaurant-namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP