apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: order-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-service
          image: amjadfqs/g1_a_order_service_k8s:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/order_service
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123"
            - name: CUSTOMER_SERVICE_URL
              value: http://localhost:8081
            # - name: RESTAURANT_SERVICE_URL
              # value: http://restaurant.service.com/
              # value: restaurant-service.restaurant-namespace.svc.cluster.local:8000
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order-namespace
spec:
  selector:
    app: order
  ports:
    - port: 8080
  type: ClusterIP
