apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: order-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: order_service
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "123"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: order-namespace
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
