name: Deploy Image

on:
  workflow_run:
    workflows: [Build and Test]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: g1_a_order-1.jar
          path: target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t amjadfqs/g1_a_order_service .
          docker tag amjadfqs/g1_a_order_service amjadfqs/g1_a_order_service:latest
          docker push amjadfqs/g1_a_order_service:latest

      - name: Build and push Docker k8s image
        run: |
          docker build -f k8s.Dockerfile -t amjadfqs/g1_a_order_service_k8s .
          docker tag amjadfqs/g1_a_order_service_k8s amjadfqs/g1_a_order_service_k8s:latest
          docker push amjadfqs/g1_a_order_service_k8s:latest
