name: Deploy Image

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"

      - name: Create secrets.properties
        run: |
          touch src/main/resources/secrets.properties
          echo MAIL_TOKEN=${{ secrets.MAIL_TOKEN }} >> src/main/resources/secrets.properties
          echo MAIL_DOMAIN=${{ secrets.MAIL_DOMAIN }} >> src/main/resources/secrets.properties
          echo MAIL_SENDER=${{ secrets.MAIL_SENDER }} >> src/main/resources/secrets.properties

      - name: Build with Maven
        run: mvn -B package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t amjadfqs/g1_a_order_service .
          docker tag amjadfqs/g1_a_order_service amjadfqs/g1_a_order_service:latest
          docker push amjadfqs/g1_a_order_service:latest

      - name: Build and push Docker k8s image
        run: |
          docker build -f k8s.Dockerfile -t amjadfqs/g1_a_order_service_k8s .
          docker tag amjadfqs/g1_a_order_service_k8s amjadfqs/g1_a_order_service_k8s:latest
          docker push amjadfqs/g1_a_order_service_k8s:latest
