name: Order Service CI/CD

on:
  push:
    branches: [ dev ]  # Trigger on the 'dev' branch
  pull_request:
    branches: [ dev ]  # Trigger on PRs to the 'dev' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'  
          cache: 'maven'

      - name: Build with Maven
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        # run: mvn -B package --file pom.xml 
        run: mvn clean install

      - name: Run tests
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        run: mvn test 
