name: Order Service CI/CD

on:
  push:
    branches: [dev] # Trigger on the 'dev' branch
  pull_request:
    branches: [dev] # Trigger on PRs to the 'dev' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: order_service
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"

      - name: Create application.properties
        run: |
          touch src/main/resources/application.properties
          echo "spring.datasource.url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/order_service" > src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.DB_USER }}" >> src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
          echo "spring.datasource.driver-class-name=org.postgresql.Driver" >> src/main/resources/application.properties
          echo "spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect" >> src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=create-drop" >> src/main/resources/application.properties

      - name: Set Spring profile for testing
        run: echo "spring.profiles.active=test" >> $GITHUB_ENV

      - name: Build with Maven
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        # run: mvn -B package --file pom.xml
        run: mvn clean install

      - name: Run tests
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        run: mvn test
