name: Create Release

on:
  push:
    branches:
      - CI/CD-auto-releasing
#   pull_request:
#     types: [closed]
#     branches:
#       - dev

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    # if: ${{ github.event.pull_request.merged }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean install

      - name: Create Release Tag
        id: create_version_tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor

      - name: Install auto-changelog (if needed)
        if: ${{ !steps.auto_changelog_check.outputs.auto_changelog_installed }}
        run: npm install -g auto-changelog

      - name: Check auto-changelog installation
        id: auto_changelog_check
        run: echo "::set-output name=auto_changelog_installed::$(command -v auto-changelog)"

      - name: Generate Changelog
        run: auto-changelog --output CHANGELOG.md --starting-version ${{ steps.create_version_tag.outputs.new_tag }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_version_tag.outputs.new_tag }}
          release_name: ${{ steps.create_version_tag.outputs.new_tag }}
          body: |
            *Changes in this release:*
            ```markdown
            <%= CHANGELOG %>
            ```
          draft: false
          prerelease: false

      - run: |
          upload_url=$(curl -sL https://api.github.com/repos/actions/checkout/releases/latest | jq -r '.upload_url')
          echo UPLOAD_URL=$upload_url >> $GITHUB_ENV
        shell: bash

      - name: Upload Release JAR
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./target/g1_a_order-1.jar
          asset_name: g1_a_order-1.jar
          asset_content_type: application/java-archive
